### ISSUE TITLE
Downloading to CSV Exports Ids not Names

### ISSUE THREAD

**Issue by tslphill** [zendesklabs/advanced_search#9]
After the 7-11-2016 update, the Export CSV option does not export names for the Assignee and Requester fields anymore. This has been an issue with the Group field for a while, but this had never been a problem for the Assignee or Requester before.

**Comment by amg4110** [comment]
<img width="1059" alt="screen shot 2016-07-14 at 11 48 44 am" src="https://cloud.githubusercontent.com/assets/7771109/16846128/3d5ef984-49b9-11e6-8a79-fc5cd1ddf950.png">
We've noticed the same thing happening. We already really miss having the names for the assignee and requester fields rather than IDs. Please fix!

**Comment by nickscroggs** [comment]
In addition to this, it no longer exports the email address associated with the requester.

**Comment by betomirand** [comment]
The reports with the emails helped me a lot. Will this feature come back ?

**Comment by mrosendin** [comment]
Hi everyone, sorry for the delay in response. I am currently working on a new release for this app. This issue will be fixed in the new release (due this week).
